### ISSUE TITLE
Stata16.1 PNG export issue

### ISSUE THREAD

**Issue by larsvilhuber** [AEADataEditor/docker-stata#3]
In principle, Stata 16.1 should be able to export PNG at the command line. However, when running `dataeditor/stata16:2021-06-02` with Docker/MacOS(non-M1), an error occurs:

```
.  graph  export "$path4/Fig1Lab1.png", width(5000) replace 
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nati
> ve Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unkno
> wn Source)
```

**Comment by larsvilhuber** [comment]
This does not happen in the "donor" Linux environment.

**Comment by larsvilhuber** [comment]
Full log file:
```
java.lang.NullPointerException
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.
> java:1262)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfig
> uration.java:225)
        at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:1
> 07)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontM
> anager.java:719)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
        at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInst
> ance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInst
> ance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.new
> Instance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java
> :490)
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.ja
> va:84)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFact
> ory.java:74)
        at java.desktop/sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(
> SunGraphicsEnvironment.java:189)
        at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamil
> yNames(SunGraphicsEnvironment.java:223)
        at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamil
> yNames(SunGraphicsEnvironment.java:251)
        at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getAvailableFont
> FamilyNames(HeadlessGraphicsEnvironment.java:75)
        at org.apache.batik.bridge.DefaultFontFamilyResolver.<clinit>(DefaultFo
> ntFamilyResolver.java:86)
        at org.apache.batik.bridge.UserAgentAdapter.getFontFamilyResolver(UserA
> gentAdapter.java:465)
        at org.apache.batik.bridge.BridgeContext.getFontFamilyResolver(BridgeCo
> ntext.java:284)
        at org.apache.batik.bridge.SVGTextElementBridge.getFontList(SVGTextElem
> entBridge.java:1518)
        at org.apache.batik.bridge.SVGTextElementBridge.getAttributeMap(SVGText
> ElementBridge.java:1597)
        at org.apache.batik.bridge.SVGTextElementBridge.fillAttributedStringBuf
> fer(SVGTextElementBridge.java:897)
        at org.apache.batik.bridge.SVGTextElementBridge.buildAttributedString(S
> VGTextElementBridge.java:850)
        at org.apache.batik.bridge.SVGTextElementBridge.computeLaidoutText(SVGT
> extElementBridge.java:630)
        at org.apache.batik.bridge.SVGTextElementBridge.buildGraphicsNode(SVGTe
> xtElementBridge.java:286)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java
> :224)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:17
> 1)
        at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstr
> actTranscoder.java:208)
        at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTra
> nscoder.java:92)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstr
> actTranscoder.java:142)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstr
> actTranscoder.java:156)
        at com.stata.plugins.SvgConverter.doConvert(SvgConverter.java:106)
        at com.stata.plugins.SvgConverter.svg2Bitmap(SvgConverter.java:163)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nati
> ve Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Nativ
> eMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(D
> elegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.stata.Javacall.load(Javacall.java:162)
        at com.stata.Javacall.load(Javacall.java:103)
```

Looks like it may have something to do with fonts.

**Comment by larsvilhuber** [comment]
Maybe see here: https://github.com/AdoptOpenJDK/openjdk-docker/issues/75
